# Generated by Django 3.1 on 2022-08-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
