# Generated by Django 3.1 on 2022-07-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220705_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variations',
            new_name='variation',
        ),
    ]
